### ISSUE TITLE
Rescue request create form needs a back button

### ISSUE THREAD

**Issue by ArtOfCode-** [ArtOfCode-/SCOT#39]
Browser back goes to the wrong place.

**Comment by epetkus** [comment]
@ArtOfCode- Hey. I would love to get this done for you. Any preference of positioning? Also if user is on Stage 2, clicks the new button back to Stage 1 (accidentally) do we need a button for back to Stage 2 (with preserved progress) or we force user to re-select location on the map/input field? Thanks.

**Comment by ArtOfCode-** [comment]
@epetkus Double points if you can make both back and forward buttons - i.e. back takes you to the previous stage, and forward to the next stage.

**Comment by izwick-schachter** [comment]
Is this irrelevant now that the form is all on one page?

**Comment by ArtOfCode-** [comment]
Might be, are

**Comment by epetkus** [comment]
This is why back/forward doesn't work, as it is the same URL. What I am about to do is literally to introduce JS based navigation for all 3 steps of the form. Which works as following:
* On form render (first step) no navigation is present
* Once on second step - button back will appear, and if navigate back, since we have selection from step one we will have forward button
* Same concept carried to the last stage 

@ArtOfCode- @izwick-schachter all cool with that?

**Comment by izwick-schachter** [comment]
The way I was thinking we could do it is by having a separate action for each stage, and separate the "Choose Location" and "Confirm Location" part. That way browser back will work as intended. We can also include back and forward buttons.

Totally JS based nav is even more awesome, if you want to do that, as long as it will cooperate with browser back. I don't know how it'll work because I've never done it, but I'm eager to see what you do @epetkus!

**Comment by ArtOfCode-** [comment]
Done with new CAD create form
